// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v1.0.0
// source: internal/api/rpc/service.proto

package rpc

import (
	context "context"
	errors "errors"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_internal_api_rpc_service_proto struct{}

func (drpcEncoding_File_internal_api_rpc_service_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return proto.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_internal_api_rpc_service_proto) MarshalAppend(buf []byte, msg drpc.Message) ([]byte, error) {
	return proto.MarshalOptions{}.MarshalAppend(buf, msg.(proto.Message))
}

func (drpcEncoding_File_internal_api_rpc_service_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return proto.Unmarshal(buf, msg.(proto.Message))
}

func (drpcEncoding_File_internal_api_rpc_service_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return protojson.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_internal_api_rpc_service_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return protojson.Unmarshal(buf, msg.(proto.Message))
}

type DRPCClusterClient interface {
	DRPCConn() drpc.Conn

	Handshake(ctx context.Context, in *Hello) (*HelloAck, error)
	HeartbeatStream(ctx context.Context) (DRPCCluster_HeartbeatStreamClient, error)
	HasChunk(ctx context.Context, in *ChunkRef) (*ChunkPresence, error)
	HasChunks(ctx context.Context, in *ChunkRefBatch) (*ChunkPresenceBatch, error)
	PutChunk(ctx context.Context) (DRPCCluster_PutChunkClient, error)
	GetChunk(ctx context.Context, in *ChunkRef) (DRPCCluster_GetChunkClient, error)
	DeleteChunkReplica(ctx context.Context, in *ChunkRef) (*Ack, error)
	AcquirePending(ctx context.Context, in *LeaseRequest) (*Ack, error)
	ReleasePending(ctx context.Context, in *LeaseRequest) (*Ack, error)
	PutMetadata(ctx context.Context, in *MetadataOp) (*MetadataAck, error)
	GetMetadata(ctx context.Context, in *MetadataKey) (*Metadata, error)
	DeleteMetadata(ctx context.Context, in *MetadataKey) (*Metadata, error)
	ListMetadata(ctx context.Context, in *ListRequest) (DRPCCluster_ListMetadataClient, error)
	PutVersion(ctx context.Context, in *MetadataOp) (*MetadataAck, error)
	GetVersion(ctx context.Context, in *MetadataKey) (*Metadata, error)
	DeleteVersion(ctx context.Context, in *MetadataKey) (*Metadata, error)
	InitiateMPU(ctx context.Context, in *MPUPart) (*Ack, error)
	PutMPUPart(ctx context.Context, in *MPUPart) (*Ack, error)
	CompleteMPU(ctx context.Context, in *MPUComplete) (*MetadataAck, error)
	AbortMPU(ctx context.Context, in *MPUAbort) (*Ack, error)
	BucketOp(ctx context.Context, in *BucketOpRequest) (*BucketOpResponse, error)
	IncRefs(ctx context.Context, in *RefDelta) (*Ack, error)
	DecRefs(ctx context.Context, in *RefDelta) (*Ack, error)
	ReplicaCatchup(ctx context.Context, in *CatchupCursor) (DRPCCluster_ReplicaCatchupClient, error)
	GetLayout(ctx context.Context, in *LayoutRequest) (*LayoutResponse, error)
	ReplicateKV(ctx context.Context, in *KVOp) (*KVAck, error)
	BulkSyncKV(ctx context.Context, in *KVBulkRequest) (DRPCCluster_BulkSyncKVClient, error)
}

type drpcClusterClient struct {
	cc drpc.Conn
}

func NewDRPCClusterClient(cc drpc.Conn) DRPCClusterClient {
	return &drpcClusterClient{cc}
}

func (c *drpcClusterClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcClusterClient) Handshake(ctx context.Context, in *Hello) (*HelloAck, error) {
	out := new(HelloAck)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/Handshake", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) HeartbeatStream(ctx context.Context) (DRPCCluster_HeartbeatStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, "/hangar.cluster.v1.Cluster/HeartbeatStream", drpcEncoding_File_internal_api_rpc_service_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcCluster_HeartbeatStreamClient{stream}
	return x, nil
}

type DRPCCluster_HeartbeatStreamClient interface {
	drpc.Stream
	Send(*Heartbeat) error
	Recv() (*Heartbeat, error)
}

type drpcCluster_HeartbeatStreamClient struct {
	drpc.Stream
}

func (x *drpcCluster_HeartbeatStreamClient) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_HeartbeatStreamClient) Send(m *Heartbeat) error {
	return x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{})
}

func (x *drpcCluster_HeartbeatStreamClient) Recv() (*Heartbeat, error) {
	m := new(Heartbeat)
	if err := x.MsgRecv(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcCluster_HeartbeatStreamClient) RecvMsg(m *Heartbeat) error {
	return x.MsgRecv(m, drpcEncoding_File_internal_api_rpc_service_proto{})
}

func (c *drpcClusterClient) HasChunk(ctx context.Context, in *ChunkRef) (*ChunkPresence, error) {
	out := new(ChunkPresence)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/HasChunk", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) HasChunks(ctx context.Context, in *ChunkRefBatch) (*ChunkPresenceBatch, error) {
	out := new(ChunkPresenceBatch)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/HasChunks", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) PutChunk(ctx context.Context) (DRPCCluster_PutChunkClient, error) {
	stream, err := c.cc.NewStream(ctx, "/hangar.cluster.v1.Cluster/PutChunk", drpcEncoding_File_internal_api_rpc_service_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcCluster_PutChunkClient{stream}
	return x, nil
}

type DRPCCluster_PutChunkClient interface {
	drpc.Stream
	Send(*ChunkData) error
	CloseAndRecv() (*PutChunkAck, error)
}

type drpcCluster_PutChunkClient struct {
	drpc.Stream
}

func (x *drpcCluster_PutChunkClient) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_PutChunkClient) Send(m *ChunkData) error {
	return x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{})
}

func (x *drpcCluster_PutChunkClient) CloseAndRecv() (*PutChunkAck, error) {
	if err := x.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PutChunkAck)
	if err := x.MsgRecv(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcCluster_PutChunkClient) CloseAndRecvMsg(m *PutChunkAck) error {
	if err := x.CloseSend(); err != nil {
		return err
	}
	return x.MsgRecv(m, drpcEncoding_File_internal_api_rpc_service_proto{})
}

func (c *drpcClusterClient) GetChunk(ctx context.Context, in *ChunkRef) (DRPCCluster_GetChunkClient, error) {
	stream, err := c.cc.NewStream(ctx, "/hangar.cluster.v1.Cluster/GetChunk", drpcEncoding_File_internal_api_rpc_service_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcCluster_GetChunkClient{stream}
	if err := x.MsgSend(in, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return nil, err
	}
	if err := x.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DRPCCluster_GetChunkClient interface {
	drpc.Stream
	Recv() (*ChunkData, error)
}

type drpcCluster_GetChunkClient struct {
	drpc.Stream
}

func (x *drpcCluster_GetChunkClient) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_GetChunkClient) Recv() (*ChunkData, error) {
	m := new(ChunkData)
	if err := x.MsgRecv(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcCluster_GetChunkClient) RecvMsg(m *ChunkData) error {
	return x.MsgRecv(m, drpcEncoding_File_internal_api_rpc_service_proto{})
}

func (c *drpcClusterClient) DeleteChunkReplica(ctx context.Context, in *ChunkRef) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/DeleteChunkReplica", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) AcquirePending(ctx context.Context, in *LeaseRequest) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/AcquirePending", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) ReleasePending(ctx context.Context, in *LeaseRequest) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/ReleasePending", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) PutMetadata(ctx context.Context, in *MetadataOp) (*MetadataAck, error) {
	out := new(MetadataAck)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/PutMetadata", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) GetMetadata(ctx context.Context, in *MetadataKey) (*Metadata, error) {
	out := new(Metadata)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/GetMetadata", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) DeleteMetadata(ctx context.Context, in *MetadataKey) (*Metadata, error) {
	out := new(Metadata)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/DeleteMetadata", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) ListMetadata(ctx context.Context, in *ListRequest) (DRPCCluster_ListMetadataClient, error) {
	stream, err := c.cc.NewStream(ctx, "/hangar.cluster.v1.Cluster/ListMetadata", drpcEncoding_File_internal_api_rpc_service_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcCluster_ListMetadataClient{stream}
	if err := x.MsgSend(in, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return nil, err
	}
	if err := x.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DRPCCluster_ListMetadataClient interface {
	drpc.Stream
	Recv() (*MetadataEntry, error)
}

type drpcCluster_ListMetadataClient struct {
	drpc.Stream
}

func (x *drpcCluster_ListMetadataClient) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_ListMetadataClient) Recv() (*MetadataEntry, error) {
	m := new(MetadataEntry)
	if err := x.MsgRecv(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcCluster_ListMetadataClient) RecvMsg(m *MetadataEntry) error {
	return x.MsgRecv(m, drpcEncoding_File_internal_api_rpc_service_proto{})
}

func (c *drpcClusterClient) PutVersion(ctx context.Context, in *MetadataOp) (*MetadataAck, error) {
	out := new(MetadataAck)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/PutVersion", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) GetVersion(ctx context.Context, in *MetadataKey) (*Metadata, error) {
	out := new(Metadata)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/GetVersion", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) DeleteVersion(ctx context.Context, in *MetadataKey) (*Metadata, error) {
	out := new(Metadata)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/DeleteVersion", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) InitiateMPU(ctx context.Context, in *MPUPart) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/InitiateMPU", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) PutMPUPart(ctx context.Context, in *MPUPart) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/PutMPUPart", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) CompleteMPU(ctx context.Context, in *MPUComplete) (*MetadataAck, error) {
	out := new(MetadataAck)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/CompleteMPU", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) AbortMPU(ctx context.Context, in *MPUAbort) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/AbortMPU", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) BucketOp(ctx context.Context, in *BucketOpRequest) (*BucketOpResponse, error) {
	out := new(BucketOpResponse)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/BucketOp", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) IncRefs(ctx context.Context, in *RefDelta) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/IncRefs", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) DecRefs(ctx context.Context, in *RefDelta) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/DecRefs", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) ReplicaCatchup(ctx context.Context, in *CatchupCursor) (DRPCCluster_ReplicaCatchupClient, error) {
	stream, err := c.cc.NewStream(ctx, "/hangar.cluster.v1.Cluster/ReplicaCatchup", drpcEncoding_File_internal_api_rpc_service_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcCluster_ReplicaCatchupClient{stream}
	if err := x.MsgSend(in, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return nil, err
	}
	if err := x.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DRPCCluster_ReplicaCatchupClient interface {
	drpc.Stream
	Recv() (*WALEntry, error)
}

type drpcCluster_ReplicaCatchupClient struct {
	drpc.Stream
}

func (x *drpcCluster_ReplicaCatchupClient) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_ReplicaCatchupClient) Recv() (*WALEntry, error) {
	m := new(WALEntry)
	if err := x.MsgRecv(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcCluster_ReplicaCatchupClient) RecvMsg(m *WALEntry) error {
	return x.MsgRecv(m, drpcEncoding_File_internal_api_rpc_service_proto{})
}

func (c *drpcClusterClient) GetLayout(ctx context.Context, in *LayoutRequest) (*LayoutResponse, error) {
	out := new(LayoutResponse)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/GetLayout", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) ReplicateKV(ctx context.Context, in *KVOp) (*KVAck, error) {
	out := new(KVAck)
	err := c.cc.Invoke(ctx, "/hangar.cluster.v1.Cluster/ReplicateKV", drpcEncoding_File_internal_api_rpc_service_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcClusterClient) BulkSyncKV(ctx context.Context, in *KVBulkRequest) (DRPCCluster_BulkSyncKVClient, error) {
	stream, err := c.cc.NewStream(ctx, "/hangar.cluster.v1.Cluster/BulkSyncKV", drpcEncoding_File_internal_api_rpc_service_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcCluster_BulkSyncKVClient{stream}
	if err := x.MsgSend(in, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return nil, err
	}
	if err := x.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DRPCCluster_BulkSyncKVClient interface {
	drpc.Stream
	Recv() (*KVEntry, error)
}

type drpcCluster_BulkSyncKVClient struct {
	drpc.Stream
}

func (x *drpcCluster_BulkSyncKVClient) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_BulkSyncKVClient) Recv() (*KVEntry, error) {
	m := new(KVEntry)
	if err := x.MsgRecv(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcCluster_BulkSyncKVClient) RecvMsg(m *KVEntry) error {
	return x.MsgRecv(m, drpcEncoding_File_internal_api_rpc_service_proto{})
}

type DRPCClusterServer interface {
	Handshake(context.Context, *Hello) (*HelloAck, error)
	HeartbeatStream(DRPCCluster_HeartbeatStreamStream) error
	HasChunk(context.Context, *ChunkRef) (*ChunkPresence, error)
	HasChunks(context.Context, *ChunkRefBatch) (*ChunkPresenceBatch, error)
	PutChunk(DRPCCluster_PutChunkStream) error
	GetChunk(*ChunkRef, DRPCCluster_GetChunkStream) error
	DeleteChunkReplica(context.Context, *ChunkRef) (*Ack, error)
	AcquirePending(context.Context, *LeaseRequest) (*Ack, error)
	ReleasePending(context.Context, *LeaseRequest) (*Ack, error)
	PutMetadata(context.Context, *MetadataOp) (*MetadataAck, error)
	GetMetadata(context.Context, *MetadataKey) (*Metadata, error)
	DeleteMetadata(context.Context, *MetadataKey) (*Metadata, error)
	ListMetadata(*ListRequest, DRPCCluster_ListMetadataStream) error
	PutVersion(context.Context, *MetadataOp) (*MetadataAck, error)
	GetVersion(context.Context, *MetadataKey) (*Metadata, error)
	DeleteVersion(context.Context, *MetadataKey) (*Metadata, error)
	InitiateMPU(context.Context, *MPUPart) (*Ack, error)
	PutMPUPart(context.Context, *MPUPart) (*Ack, error)
	CompleteMPU(context.Context, *MPUComplete) (*MetadataAck, error)
	AbortMPU(context.Context, *MPUAbort) (*Ack, error)
	BucketOp(context.Context, *BucketOpRequest) (*BucketOpResponse, error)
	IncRefs(context.Context, *RefDelta) (*Ack, error)
	DecRefs(context.Context, *RefDelta) (*Ack, error)
	ReplicaCatchup(*CatchupCursor, DRPCCluster_ReplicaCatchupStream) error
	GetLayout(context.Context, *LayoutRequest) (*LayoutResponse, error)
	ReplicateKV(context.Context, *KVOp) (*KVAck, error)
	BulkSyncKV(*KVBulkRequest, DRPCCluster_BulkSyncKVStream) error
}

type DRPCClusterUnimplementedServer struct{}

func (s *DRPCClusterUnimplementedServer) Handshake(context.Context, *Hello) (*HelloAck, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) HeartbeatStream(DRPCCluster_HeartbeatStreamStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) HasChunk(context.Context, *ChunkRef) (*ChunkPresence, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) HasChunks(context.Context, *ChunkRefBatch) (*ChunkPresenceBatch, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) PutChunk(DRPCCluster_PutChunkStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) GetChunk(*ChunkRef, DRPCCluster_GetChunkStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) DeleteChunkReplica(context.Context, *ChunkRef) (*Ack, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) AcquirePending(context.Context, *LeaseRequest) (*Ack, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) ReleasePending(context.Context, *LeaseRequest) (*Ack, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) PutMetadata(context.Context, *MetadataOp) (*MetadataAck, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) GetMetadata(context.Context, *MetadataKey) (*Metadata, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) DeleteMetadata(context.Context, *MetadataKey) (*Metadata, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) ListMetadata(*ListRequest, DRPCCluster_ListMetadataStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) PutVersion(context.Context, *MetadataOp) (*MetadataAck, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) GetVersion(context.Context, *MetadataKey) (*Metadata, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) DeleteVersion(context.Context, *MetadataKey) (*Metadata, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) InitiateMPU(context.Context, *MPUPart) (*Ack, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) PutMPUPart(context.Context, *MPUPart) (*Ack, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) CompleteMPU(context.Context, *MPUComplete) (*MetadataAck, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) AbortMPU(context.Context, *MPUAbort) (*Ack, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) BucketOp(context.Context, *BucketOpRequest) (*BucketOpResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) IncRefs(context.Context, *RefDelta) (*Ack, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) DecRefs(context.Context, *RefDelta) (*Ack, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) ReplicaCatchup(*CatchupCursor, DRPCCluster_ReplicaCatchupStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) GetLayout(context.Context, *LayoutRequest) (*LayoutResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) ReplicateKV(context.Context, *KVOp) (*KVAck, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCClusterUnimplementedServer) BulkSyncKV(*KVBulkRequest, DRPCCluster_BulkSyncKVStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCClusterDescription struct{}

func (DRPCClusterDescription) NumMethods() int { return 27 }

func (DRPCClusterDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/hangar.cluster.v1.Cluster/Handshake", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					Handshake(
						ctx,
						in1.(*Hello),
					)
			}, DRPCClusterServer.Handshake, true
	case 1:
		return "/hangar.cluster.v1.Cluster/HeartbeatStream", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCClusterServer).
					HeartbeatStream(
						&drpcCluster_HeartbeatStreamStream{in1.(drpc.Stream)},
					)
			}, DRPCClusterServer.HeartbeatStream, true
	case 2:
		return "/hangar.cluster.v1.Cluster/HasChunk", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					HasChunk(
						ctx,
						in1.(*ChunkRef),
					)
			}, DRPCClusterServer.HasChunk, true
	case 3:
		return "/hangar.cluster.v1.Cluster/HasChunks", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					HasChunks(
						ctx,
						in1.(*ChunkRefBatch),
					)
			}, DRPCClusterServer.HasChunks, true
	case 4:
		return "/hangar.cluster.v1.Cluster/PutChunk", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCClusterServer).
					PutChunk(
						&drpcCluster_PutChunkStream{in1.(drpc.Stream)},
					)
			}, DRPCClusterServer.PutChunk, true
	case 5:
		return "/hangar.cluster.v1.Cluster/GetChunk", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCClusterServer).
					GetChunk(
						in1.(*ChunkRef),
						&drpcCluster_GetChunkStream{in2.(drpc.Stream)},
					)
			}, DRPCClusterServer.GetChunk, true
	case 6:
		return "/hangar.cluster.v1.Cluster/DeleteChunkReplica", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					DeleteChunkReplica(
						ctx,
						in1.(*ChunkRef),
					)
			}, DRPCClusterServer.DeleteChunkReplica, true
	case 7:
		return "/hangar.cluster.v1.Cluster/AcquirePending", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					AcquirePending(
						ctx,
						in1.(*LeaseRequest),
					)
			}, DRPCClusterServer.AcquirePending, true
	case 8:
		return "/hangar.cluster.v1.Cluster/ReleasePending", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					ReleasePending(
						ctx,
						in1.(*LeaseRequest),
					)
			}, DRPCClusterServer.ReleasePending, true
	case 9:
		return "/hangar.cluster.v1.Cluster/PutMetadata", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					PutMetadata(
						ctx,
						in1.(*MetadataOp),
					)
			}, DRPCClusterServer.PutMetadata, true
	case 10:
		return "/hangar.cluster.v1.Cluster/GetMetadata", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					GetMetadata(
						ctx,
						in1.(*MetadataKey),
					)
			}, DRPCClusterServer.GetMetadata, true
	case 11:
		return "/hangar.cluster.v1.Cluster/DeleteMetadata", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					DeleteMetadata(
						ctx,
						in1.(*MetadataKey),
					)
			}, DRPCClusterServer.DeleteMetadata, true
	case 12:
		return "/hangar.cluster.v1.Cluster/ListMetadata", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCClusterServer).
					ListMetadata(
						in1.(*ListRequest),
						&drpcCluster_ListMetadataStream{in2.(drpc.Stream)},
					)
			}, DRPCClusterServer.ListMetadata, true
	case 13:
		return "/hangar.cluster.v1.Cluster/PutVersion", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					PutVersion(
						ctx,
						in1.(*MetadataOp),
					)
			}, DRPCClusterServer.PutVersion, true
	case 14:
		return "/hangar.cluster.v1.Cluster/GetVersion", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					GetVersion(
						ctx,
						in1.(*MetadataKey),
					)
			}, DRPCClusterServer.GetVersion, true
	case 15:
		return "/hangar.cluster.v1.Cluster/DeleteVersion", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					DeleteVersion(
						ctx,
						in1.(*MetadataKey),
					)
			}, DRPCClusterServer.DeleteVersion, true
	case 16:
		return "/hangar.cluster.v1.Cluster/InitiateMPU", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					InitiateMPU(
						ctx,
						in1.(*MPUPart),
					)
			}, DRPCClusterServer.InitiateMPU, true
	case 17:
		return "/hangar.cluster.v1.Cluster/PutMPUPart", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					PutMPUPart(
						ctx,
						in1.(*MPUPart),
					)
			}, DRPCClusterServer.PutMPUPart, true
	case 18:
		return "/hangar.cluster.v1.Cluster/CompleteMPU", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					CompleteMPU(
						ctx,
						in1.(*MPUComplete),
					)
			}, DRPCClusterServer.CompleteMPU, true
	case 19:
		return "/hangar.cluster.v1.Cluster/AbortMPU", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					AbortMPU(
						ctx,
						in1.(*MPUAbort),
					)
			}, DRPCClusterServer.AbortMPU, true
	case 20:
		return "/hangar.cluster.v1.Cluster/BucketOp", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					BucketOp(
						ctx,
						in1.(*BucketOpRequest),
					)
			}, DRPCClusterServer.BucketOp, true
	case 21:
		return "/hangar.cluster.v1.Cluster/IncRefs", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					IncRefs(
						ctx,
						in1.(*RefDelta),
					)
			}, DRPCClusterServer.IncRefs, true
	case 22:
		return "/hangar.cluster.v1.Cluster/DecRefs", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					DecRefs(
						ctx,
						in1.(*RefDelta),
					)
			}, DRPCClusterServer.DecRefs, true
	case 23:
		return "/hangar.cluster.v1.Cluster/ReplicaCatchup", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCClusterServer).
					ReplicaCatchup(
						in1.(*CatchupCursor),
						&drpcCluster_ReplicaCatchupStream{in2.(drpc.Stream)},
					)
			}, DRPCClusterServer.ReplicaCatchup, true
	case 24:
		return "/hangar.cluster.v1.Cluster/GetLayout", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					GetLayout(
						ctx,
						in1.(*LayoutRequest),
					)
			}, DRPCClusterServer.GetLayout, true
	case 25:
		return "/hangar.cluster.v1.Cluster/ReplicateKV", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCClusterServer).
					ReplicateKV(
						ctx,
						in1.(*KVOp),
					)
			}, DRPCClusterServer.ReplicateKV, true
	case 26:
		return "/hangar.cluster.v1.Cluster/BulkSyncKV", drpcEncoding_File_internal_api_rpc_service_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCClusterServer).
					BulkSyncKV(
						in1.(*KVBulkRequest),
						&drpcCluster_BulkSyncKVStream{in2.(drpc.Stream)},
					)
			}, DRPCClusterServer.BulkSyncKV, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterCluster(mux drpc.Mux, impl DRPCClusterServer) error {
	return mux.Register(impl, DRPCClusterDescription{})
}

type DRPCCluster_HandshakeStream interface {
	drpc.Stream
	SendAndClose(*HelloAck) error
}

type drpcCluster_HandshakeStream struct {
	drpc.Stream
}

func (x *drpcCluster_HandshakeStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_HandshakeStream) SendAndClose(m *HelloAck) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_HeartbeatStreamStream interface {
	drpc.Stream
	Send(*Heartbeat) error
	Recv() (*Heartbeat, error)
}

type drpcCluster_HeartbeatStreamStream struct {
	drpc.Stream
}

func (x *drpcCluster_HeartbeatStreamStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_HeartbeatStreamStream) Send(m *Heartbeat) error {
	return x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{})
}

func (x *drpcCluster_HeartbeatStreamStream) Recv() (*Heartbeat, error) {
	m := new(Heartbeat)
	if err := x.MsgRecv(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcCluster_HeartbeatStreamStream) RecvMsg(m *Heartbeat) error {
	return x.MsgRecv(m, drpcEncoding_File_internal_api_rpc_service_proto{})
}

type DRPCCluster_HasChunkStream interface {
	drpc.Stream
	SendAndClose(*ChunkPresence) error
}

type drpcCluster_HasChunkStream struct {
	drpc.Stream
}

func (x *drpcCluster_HasChunkStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_HasChunkStream) SendAndClose(m *ChunkPresence) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_HasChunksStream interface {
	drpc.Stream
	SendAndClose(*ChunkPresenceBatch) error
}

type drpcCluster_HasChunksStream struct {
	drpc.Stream
}

func (x *drpcCluster_HasChunksStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_HasChunksStream) SendAndClose(m *ChunkPresenceBatch) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_PutChunkStream interface {
	drpc.Stream
	SendAndClose(*PutChunkAck) error
	Recv() (*ChunkData, error)
}

type drpcCluster_PutChunkStream struct {
	drpc.Stream
}

func (x *drpcCluster_PutChunkStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_PutChunkStream) SendAndClose(m *PutChunkAck) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

func (x *drpcCluster_PutChunkStream) Recv() (*ChunkData, error) {
	m := new(ChunkData)
	if err := x.MsgRecv(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcCluster_PutChunkStream) RecvMsg(m *ChunkData) error {
	return x.MsgRecv(m, drpcEncoding_File_internal_api_rpc_service_proto{})
}

type DRPCCluster_GetChunkStream interface {
	drpc.Stream
	Send(*ChunkData) error
}

type drpcCluster_GetChunkStream struct {
	drpc.Stream
}

func (x *drpcCluster_GetChunkStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_GetChunkStream) Send(m *ChunkData) error {
	return x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{})
}

type DRPCCluster_DeleteChunkReplicaStream interface {
	drpc.Stream
	SendAndClose(*Ack) error
}

type drpcCluster_DeleteChunkReplicaStream struct {
	drpc.Stream
}

func (x *drpcCluster_DeleteChunkReplicaStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_DeleteChunkReplicaStream) SendAndClose(m *Ack) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_AcquirePendingStream interface {
	drpc.Stream
	SendAndClose(*Ack) error
}

type drpcCluster_AcquirePendingStream struct {
	drpc.Stream
}

func (x *drpcCluster_AcquirePendingStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_AcquirePendingStream) SendAndClose(m *Ack) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_ReleasePendingStream interface {
	drpc.Stream
	SendAndClose(*Ack) error
}

type drpcCluster_ReleasePendingStream struct {
	drpc.Stream
}

func (x *drpcCluster_ReleasePendingStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_ReleasePendingStream) SendAndClose(m *Ack) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_PutMetadataStream interface {
	drpc.Stream
	SendAndClose(*MetadataAck) error
}

type drpcCluster_PutMetadataStream struct {
	drpc.Stream
}

func (x *drpcCluster_PutMetadataStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_PutMetadataStream) SendAndClose(m *MetadataAck) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_GetMetadataStream interface {
	drpc.Stream
	SendAndClose(*Metadata) error
}

type drpcCluster_GetMetadataStream struct {
	drpc.Stream
}

func (x *drpcCluster_GetMetadataStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_GetMetadataStream) SendAndClose(m *Metadata) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_DeleteMetadataStream interface {
	drpc.Stream
	SendAndClose(*Metadata) error
}

type drpcCluster_DeleteMetadataStream struct {
	drpc.Stream
}

func (x *drpcCluster_DeleteMetadataStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_DeleteMetadataStream) SendAndClose(m *Metadata) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_ListMetadataStream interface {
	drpc.Stream
	Send(*MetadataEntry) error
}

type drpcCluster_ListMetadataStream struct {
	drpc.Stream
}

func (x *drpcCluster_ListMetadataStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_ListMetadataStream) Send(m *MetadataEntry) error {
	return x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{})
}

type DRPCCluster_PutVersionStream interface {
	drpc.Stream
	SendAndClose(*MetadataAck) error
}

type drpcCluster_PutVersionStream struct {
	drpc.Stream
}

func (x *drpcCluster_PutVersionStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_PutVersionStream) SendAndClose(m *MetadataAck) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_GetVersionStream interface {
	drpc.Stream
	SendAndClose(*Metadata) error
}

type drpcCluster_GetVersionStream struct {
	drpc.Stream
}

func (x *drpcCluster_GetVersionStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_GetVersionStream) SendAndClose(m *Metadata) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_DeleteVersionStream interface {
	drpc.Stream
	SendAndClose(*Metadata) error
}

type drpcCluster_DeleteVersionStream struct {
	drpc.Stream
}

func (x *drpcCluster_DeleteVersionStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_DeleteVersionStream) SendAndClose(m *Metadata) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_InitiateMPUStream interface {
	drpc.Stream
	SendAndClose(*Ack) error
}

type drpcCluster_InitiateMPUStream struct {
	drpc.Stream
}

func (x *drpcCluster_InitiateMPUStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_InitiateMPUStream) SendAndClose(m *Ack) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_PutMPUPartStream interface {
	drpc.Stream
	SendAndClose(*Ack) error
}

type drpcCluster_PutMPUPartStream struct {
	drpc.Stream
}

func (x *drpcCluster_PutMPUPartStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_PutMPUPartStream) SendAndClose(m *Ack) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_CompleteMPUStream interface {
	drpc.Stream
	SendAndClose(*MetadataAck) error
}

type drpcCluster_CompleteMPUStream struct {
	drpc.Stream
}

func (x *drpcCluster_CompleteMPUStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_CompleteMPUStream) SendAndClose(m *MetadataAck) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_AbortMPUStream interface {
	drpc.Stream
	SendAndClose(*Ack) error
}

type drpcCluster_AbortMPUStream struct {
	drpc.Stream
}

func (x *drpcCluster_AbortMPUStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_AbortMPUStream) SendAndClose(m *Ack) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_BucketOpStream interface {
	drpc.Stream
	SendAndClose(*BucketOpResponse) error
}

type drpcCluster_BucketOpStream struct {
	drpc.Stream
}

func (x *drpcCluster_BucketOpStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_BucketOpStream) SendAndClose(m *BucketOpResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_IncRefsStream interface {
	drpc.Stream
	SendAndClose(*Ack) error
}

type drpcCluster_IncRefsStream struct {
	drpc.Stream
}

func (x *drpcCluster_IncRefsStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_IncRefsStream) SendAndClose(m *Ack) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_DecRefsStream interface {
	drpc.Stream
	SendAndClose(*Ack) error
}

type drpcCluster_DecRefsStream struct {
	drpc.Stream
}

func (x *drpcCluster_DecRefsStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_DecRefsStream) SendAndClose(m *Ack) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_ReplicaCatchupStream interface {
	drpc.Stream
	Send(*WALEntry) error
}

type drpcCluster_ReplicaCatchupStream struct {
	drpc.Stream
}

func (x *drpcCluster_ReplicaCatchupStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_ReplicaCatchupStream) Send(m *WALEntry) error {
	return x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{})
}

type DRPCCluster_GetLayoutStream interface {
	drpc.Stream
	SendAndClose(*LayoutResponse) error
}

type drpcCluster_GetLayoutStream struct {
	drpc.Stream
}

func (x *drpcCluster_GetLayoutStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_GetLayoutStream) SendAndClose(m *LayoutResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_ReplicateKVStream interface {
	drpc.Stream
	SendAndClose(*KVAck) error
}

type drpcCluster_ReplicateKVStream struct {
	drpc.Stream
}

func (x *drpcCluster_ReplicateKVStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_ReplicateKVStream) SendAndClose(m *KVAck) error {
	if err := x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCluster_BulkSyncKVStream interface {
	drpc.Stream
	Send(*KVEntry) error
}

type drpcCluster_BulkSyncKVStream struct {
	drpc.Stream
}

func (x *drpcCluster_BulkSyncKVStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcCluster_BulkSyncKVStream) Send(m *KVEntry) error {
	return x.MsgSend(m, drpcEncoding_File_internal_api_rpc_service_proto{})
}
