// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/api/rpc/service.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Ts            int64                  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Hmac          []byte                 `protobuf:"bytes,4,opt,name=hmac,proto3" json:"hmac,omitempty"`
	ProtoVersion  uint32                 `protobuf:"varint,5,opt,name=proto_version,json=protoVersion,proto3" json:"proto_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Hello) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Hello) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Hello) GetHmac() []byte {
	if x != nil {
		return x.Hmac
	}
	return nil
}

func (x *Hello) GetProtoVersion() uint32 {
	if x != nil {
		return x.ProtoVersion
	}
	return 0
}

type HelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ViewVersion   uint64                 `protobuf:"varint,3,opt,name=view_version,json=viewVersion,proto3" json:"view_version,omitempty"`
	LayoutVersion uint64                 `protobuf:"varint,4,opt,name=layout_version,json=layoutVersion,proto3" json:"layout_version,omitempty"`
	ProtoVersion  uint32                 `protobuf:"varint,5,opt,name=proto_version,json=protoVersion,proto3" json:"proto_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{1}
}

func (x *HelloAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HelloAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *HelloAck) GetViewVersion() uint64 {
	if x != nil {
		return x.ViewVersion
	}
	return 0
}

func (x *HelloAck) GetLayoutVersion() uint64 {
	if x != nil {
		return x.LayoutVersion
	}
	return 0
}

func (x *HelloAck) GetProtoVersion() uint32 {
	if x != nil {
		return x.ProtoVersion
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	ViewVersion   uint64                 `protobuf:"varint,3,opt,name=view_version,json=viewVersion,proto3" json:"view_version,omitempty"`
	LayoutVersion uint64                 `protobuf:"varint,4,opt,name=layout_version,json=layoutVersion,proto3" json:"layout_version,omitempty"`
	GcLeaderHint  string                 `protobuf:"bytes,5,opt,name=gc_leader_hint,json=gcLeaderHint,proto3" json:"gc_leader_hint,omitempty"`
	Ts            int64                  `protobuf:"varint,6,opt,name=ts,proto3" json:"ts,omitempty"`
	LoadScore     uint64                 `protobuf:"varint,7,opt,name=load_score,json=loadScore,proto3" json:"load_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Heartbeat) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Heartbeat) GetViewVersion() uint64 {
	if x != nil {
		return x.ViewVersion
	}
	return 0
}

func (x *Heartbeat) GetLayoutVersion() uint64 {
	if x != nil {
		return x.LayoutVersion
	}
	return 0
}

func (x *Heartbeat) GetGcLeaderHint() string {
	if x != nil {
		return x.GcLeaderHint
	}
	return ""
}

func (x *Heartbeat) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Heartbeat) GetLoadScore() uint64 {
	if x != nil {
		return x.LoadScore
	}
	return 0
}

type ChunkRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ShardIdx      int32                  `protobuf:"varint,2,opt,name=shard_idx,json=shardIdx,proto3" json:"shard_idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRef) Reset() {
	*x = ChunkRef{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRef) ProtoMessage() {}

func (x *ChunkRef) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRef.ProtoReflect.Descriptor instead.
func (*ChunkRef) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{3}
}

func (x *ChunkRef) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ChunkRef) GetShardIdx() int32 {
	if x != nil {
		return x.ShardIdx
	}
	return 0
}

type ChunkPresence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ShardIdx      int32                  `protobuf:"varint,2,opt,name=shard_idx,json=shardIdx,proto3" json:"shard_idx,omitempty"`
	Present       bool                   `protobuf:"varint,3,opt,name=present,proto3" json:"present,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkPresence) Reset() {
	*x = ChunkPresence{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkPresence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkPresence) ProtoMessage() {}

func (x *ChunkPresence) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkPresence.ProtoReflect.Descriptor instead.
func (*ChunkPresence) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{4}
}

func (x *ChunkPresence) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ChunkPresence) GetShardIdx() int32 {
	if x != nil {
		return x.ShardIdx
	}
	return 0
}

func (x *ChunkPresence) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

type ChunkPresenceBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ChunkPresence       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkPresenceBatch) Reset() {
	*x = ChunkPresenceBatch{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkPresenceBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkPresenceBatch) ProtoMessage() {}

func (x *ChunkPresenceBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkPresenceBatch.ProtoReflect.Descriptor instead.
func (*ChunkPresenceBatch) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{5}
}

func (x *ChunkPresenceBatch) GetEntries() []*ChunkPresence {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ChunkRefBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refs          []*ChunkRef            `protobuf:"bytes,1,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRefBatch) Reset() {
	*x = ChunkRefBatch{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRefBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRefBatch) ProtoMessage() {}

func (x *ChunkRefBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRefBatch.ProtoReflect.Descriptor instead.
func (*ChunkRefBatch) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{6}
}

func (x *ChunkRefBatch) GetRefs() []*ChunkRef {
	if x != nil {
		return x.Refs
	}
	return nil
}

type ChunkData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ShardIdx      int32                  `protobuf:"varint,2,opt,name=shard_idx,json=shardIdx,proto3" json:"shard_idx,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Last          bool                   `protobuf:"varint,4,opt,name=last,proto3" json:"last,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkData) Reset() {
	*x = ChunkData{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkData) ProtoMessage() {}

func (x *ChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkData.ProtoReflect.Descriptor instead.
func (*ChunkData) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{7}
}

func (x *ChunkData) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ChunkData) GetShardIdx() int32 {
	if x != nil {
		return x.ShardIdx
	}
	return 0
}

func (x *ChunkData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChunkData) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

func (x *ChunkData) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PutChunkAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stored        bool                   `protobuf:"varint,1,opt,name=stored,proto3" json:"stored,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunkAck) Reset() {
	*x = PutChunkAck{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunkAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunkAck) ProtoMessage() {}

func (x *PutChunkAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunkAck.ProtoReflect.Descriptor instead.
func (*PutChunkAck) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{8}
}

func (x *PutChunkAck) GetStored() bool {
	if x != nil {
		return x.Stored
	}
	return false
}

func (x *PutChunkAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{9}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MetadataKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	VersionId     string                 `protobuf:"bytes,3,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataKey) Reset() {
	*x = MetadataKey{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataKey) ProtoMessage() {}

func (x *MetadataKey) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataKey.ProtoReflect.Descriptor instead.
func (*MetadataKey) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{10}
}

func (x *MetadataKey) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *MetadataKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetadataKey) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

type MetadataOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	OpId          string                 `protobuf:"bytes,3,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataOp) Reset() {
	*x = MetadataOp{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataOp) ProtoMessage() {}

func (x *MetadataOp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataOp.ProtoReflect.Descriptor instead.
func (*MetadataOp) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{11}
}

func (x *MetadataOp) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *MetadataOp) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MetadataOp) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

func (x *MetadataOp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{12}
}

func (x *Metadata) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *Metadata) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MetadataAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	WalSeq        uint64                 `protobuf:"varint,3,opt,name=wal_seq,json=walSeq,proto3" json:"wal_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataAck) Reset() {
	*x = MetadataAck{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataAck) ProtoMessage() {}

func (x *MetadataAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataAck.ProtoReflect.Descriptor instead.
func (*MetadataAck) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{13}
}

func (x *MetadataAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MetadataAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MetadataAck) GetWalSeq() uint64 {
	if x != nil {
		return x.WalSeq
	}
	return 0
}

type ListRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Bucket            string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Prefix            string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	StartAfter        string                 `protobuf:"bytes,3,opt,name=start_after,json=startAfter,proto3" json:"start_after,omitempty"`
	ContinuationToken string                 `protobuf:"bytes,4,opt,name=continuation_token,json=continuationToken,proto3" json:"continuation_token,omitempty"`
	MaxKeys           int32                  `protobuf:"varint,5,opt,name=max_keys,json=maxKeys,proto3" json:"max_keys,omitempty"`
	Delimiter         string                 `protobuf:"bytes,6,opt,name=delimiter,proto3" json:"delimiter,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListRequest) GetStartAfter() string {
	if x != nil {
		return x.StartAfter
	}
	return ""
}

func (x *ListRequest) GetContinuationToken() string {
	if x != nil {
		return x.ContinuationToken
	}
	return ""
}

func (x *ListRequest) GetMaxKeys() int32 {
	if x != nil {
		return x.MaxKeys
	}
	return 0
}

func (x *ListRequest) GetDelimiter() string {
	if x != nil {
		return x.Delimiter
	}
	return ""
}

type MetadataEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataEntry) Reset() {
	*x = MetadataEntry{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataEntry) ProtoMessage() {}

func (x *MetadataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataEntry.ProtoReflect.Descriptor instead.
func (*MetadataEntry) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{15}
}

func (x *MetadataEntry) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *MetadataEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetadataEntry) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MPUPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	UploadId      string                 `protobuf:"bytes,3,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	PartNumber    int32                  `protobuf:"varint,4,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	PartData      []byte                 `protobuf:"bytes,5,opt,name=part_data,json=partData,proto3" json:"part_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPUPart) Reset() {
	*x = MPUPart{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPUPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPUPart) ProtoMessage() {}

func (x *MPUPart) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPUPart.ProtoReflect.Descriptor instead.
func (*MPUPart) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{16}
}

func (x *MPUPart) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *MPUPart) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MPUPart) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *MPUPart) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *MPUPart) GetPartData() []byte {
	if x != nil {
		return x.PartData
	}
	return nil
}

type MPUComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	UploadId      string                 `protobuf:"bytes,3,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	PartNumbers   []int32                `protobuf:"varint,4,rep,packed,name=part_numbers,json=partNumbers,proto3" json:"part_numbers,omitempty"`
	PartEtags     []string               `protobuf:"bytes,5,rep,name=part_etags,json=partEtags,proto3" json:"part_etags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPUComplete) Reset() {
	*x = MPUComplete{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPUComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPUComplete) ProtoMessage() {}

func (x *MPUComplete) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPUComplete.ProtoReflect.Descriptor instead.
func (*MPUComplete) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{17}
}

func (x *MPUComplete) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *MPUComplete) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MPUComplete) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *MPUComplete) GetPartNumbers() []int32 {
	if x != nil {
		return x.PartNumbers
	}
	return nil
}

func (x *MPUComplete) GetPartEtags() []string {
	if x != nil {
		return x.PartEtags
	}
	return nil
}

type MPUAbort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	UploadId      string                 `protobuf:"bytes,3,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPUAbort) Reset() {
	*x = MPUAbort{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPUAbort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPUAbort) ProtoMessage() {}

func (x *MPUAbort) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPUAbort.ProtoReflect.Descriptor instead.
func (*MPUAbort) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{18}
}

func (x *MPUAbort) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *MPUAbort) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MPUAbort) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type BucketOpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketOpRequest) Reset() {
	*x = BucketOpRequest{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketOpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketOpRequest) ProtoMessage() {}

func (x *BucketOpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketOpRequest.ProtoReflect.Descriptor instead.
func (*BucketOpRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{19}
}

func (x *BucketOpRequest) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *BucketOpRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *BucketOpRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type BucketOpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketOpResponse) Reset() {
	*x = BucketOpResponse{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketOpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketOpResponse) ProtoMessage() {}

func (x *BucketOpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketOpResponse.ProtoReflect.Descriptor instead.
func (*BucketOpResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{20}
}

func (x *BucketOpResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *BucketOpResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RefDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        []string               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	OpId          string                 `protobuf:"bytes,2,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefDelta) Reset() {
	*x = RefDelta{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefDelta) ProtoMessage() {}

func (x *RefDelta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefDelta.ProtoReflect.Descriptor instead.
func (*RefDelta) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{21}
}

func (x *RefDelta) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

func (x *RefDelta) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

type LeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	LeaseId       string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRequest) Reset() {
	*x = LeaseRequest{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRequest) ProtoMessage() {}

func (x *LeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRequest.ProtoReflect.Descriptor instead.
func (*LeaseRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{22}
}

func (x *LeaseRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *LeaseRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *LeaseRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type CatchupCursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	LastSeq       uint64                 `protobuf:"varint,2,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatchupCursor) Reset() {
	*x = CatchupCursor{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchupCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchupCursor) ProtoMessage() {}

func (x *CatchupCursor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchupCursor.ProtoReflect.Descriptor instead.
func (*CatchupCursor) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{23}
}

func (x *CatchupCursor) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *CatchupCursor) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

type WALEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Ts            int64                  `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	OpType        string                 `protobuf:"bytes,3,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALEntry) Reset() {
	*x = WALEntry{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALEntry) ProtoMessage() {}

func (x *WALEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALEntry.ProtoReflect.Descriptor instead.
func (*WALEntry) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{24}
}

func (x *WALEntry) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *WALEntry) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *WALEntry) GetOpType() string {
	if x != nil {
		return x.OpType
	}
	return ""
}

func (x *WALEntry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type LayoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayoutRequest) Reset() {
	*x = LayoutRequest{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayoutRequest) ProtoMessage() {}

func (x *LayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayoutRequest.ProtoReflect.Descriptor instead.
func (*LayoutRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{25}
}

func (x *LayoutRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type LayoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignedLayout  []byte                 `protobuf:"bytes,1,opt,name=signed_layout,json=signedLayout,proto3" json:"signed_layout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayoutResponse) Reset() {
	*x = LayoutResponse{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayoutResponse) ProtoMessage() {}

func (x *LayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayoutResponse.ProtoReflect.Descriptor instead.
func (*LayoutResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{26}
}

func (x *LayoutResponse) GetSignedLayout() []byte {
	if x != nil {
		return x.SignedLayout
	}
	return nil
}

type KVOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVOp) Reset() {
	*x = KVOp{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVOp) ProtoMessage() {}

func (x *KVOp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVOp.ProtoReflect.Descriptor instead.
func (*KVOp) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{27}
}

func (x *KVOp) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *KVOp) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KVOp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type KVAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVAck) Reset() {
	*x = KVAck{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVAck) ProtoMessage() {}

func (x *KVAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVAck.ProtoReflect.Descriptor instead.
func (*KVAck) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{28}
}

func (x *KVAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *KVAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type KVBulkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefixes      [][]byte               `protobuf:"bytes,1,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVBulkRequest) Reset() {
	*x = KVBulkRequest{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVBulkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVBulkRequest) ProtoMessage() {}

func (x *KVBulkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVBulkRequest.ProtoReflect.Descriptor instead.
func (*KVBulkRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{29}
}

func (x *KVBulkRequest) GetPrefixes() [][]byte {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

type KVEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVEntry) Reset() {
	*x = KVEntry{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVEntry) ProtoMessage() {}

func (x *KVEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVEntry.ProtoReflect.Descriptor instead.
func (*KVEntry) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{30}
}

func (x *KVEntry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KVEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Zone          string                 `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	Capacity      int64                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{31}
}

func (x *JoinRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JoinRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *JoinRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *JoinRequest) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *JoinRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	SignedLayout  []byte                 `protobuf:"bytes,3,opt,name=signed_layout,json=signedLayout,proto3" json:"signed_layout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_internal_api_rpc_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_rpc_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_rpc_service_proto_rawDescGZIP(), []int{32}
}

func (x *JoinResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *JoinResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JoinResponse) GetSignedLayout() []byte {
	if x != nil {
		return x.SignedLayout
	}
	return nil
}

var File_internal_api_rpc_service_proto protoreflect.FileDescriptor

const file_internal_api_rpc_service_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/api/rpc/service.proto\x12\x11hangar.cluster.v1\"\x7f\n" +
	"\x05Hello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x03R\x02ts\x12\x12\n" +
	"\x04hmac\x18\x04 \x01(\fR\x04hmac\x12#\n" +
	"\rproto_version\x18\x05 \x01(\rR\fprotoVersion\"\xad\x01\n" +
	"\bHelloAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12!\n" +
	"\fview_version\x18\x03 \x01(\x04R\vviewVersion\x12%\n" +
	"\x0elayout_version\x18\x04 \x01(\x04R\rlayoutVersion\x12#\n" +
	"\rproto_version\x18\x05 \x01(\rR\fprotoVersion\"\xe3\x01\n" +
	"\tHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12!\n" +
	"\fview_version\x18\x03 \x01(\x04R\vviewVersion\x12%\n" +
	"\x0elayout_version\x18\x04 \x01(\x04R\rlayoutVersion\x12$\n" +
	"\x0egc_leader_hint\x18\x05 \x01(\tR\fgcLeaderHint\x12\x0e\n" +
	"\x02ts\x18\x06 \x01(\x03R\x02ts\x12\x1d\n" +
	"\n" +
	"load_score\x18\a \x01(\x04R\tloadScore\";\n" +
	"\bChunkRef\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1b\n" +
	"\tshard_idx\x18\x02 \x01(\x05R\bshardIdx\"Z\n" +
	"\rChunkPresence\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1b\n" +
	"\tshard_idx\x18\x02 \x01(\x05R\bshardIdx\x12\x18\n" +
	"\apresent\x18\x03 \x01(\bR\apresent\"P\n" +
	"\x12ChunkPresenceBatch\x12:\n" +
	"\aentries\x18\x01 \x03(\v2 .hangar.cluster.v1.ChunkPresenceR\aentries\"@\n" +
	"\rChunkRefBatch\x12/\n" +
	"\x04refs\x18\x01 \x03(\v2\x1b.hangar.cluster.v1.ChunkRefR\x04refs\"~\n" +
	"\tChunkData\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1b\n" +
	"\tshard_idx\x18\x02 \x01(\x05R\bshardIdx\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x12\n" +
	"\x04last\x18\x04 \x01(\bR\x04last\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\";\n" +
	"\vPutChunkAck\x12\x16\n" +
	"\x06stored\x18\x01 \x01(\bR\x06stored\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"+\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"V\n" +
	"\vMetadataKey\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"version_id\x18\x03 \x01(\tR\tversionId\"g\n" +
	"\n" +
	"MetadataOp\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\fR\bmetadata\x12\x13\n" +
	"\x05op_id\x18\x03 \x01(\tR\x04opId\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\"<\n" +
	"\bMetadata\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\fR\bmetadata\"L\n" +
	"\vMetadataAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x17\n" +
	"\awal_seq\x18\x03 \x01(\x04R\x06walSeq\"\xc6\x01\n" +
	"\vListRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x1f\n" +
	"\vstart_after\x18\x03 \x01(\tR\n" +
	"startAfter\x12-\n" +
	"\x12continuation_token\x18\x04 \x01(\tR\x11continuationToken\x12\x19\n" +
	"\bmax_keys\x18\x05 \x01(\x05R\amaxKeys\x12\x1c\n" +
	"\tdelimiter\x18\x06 \x01(\tR\tdelimiter\"U\n" +
	"\rMetadataEntry\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\fR\bmetadata\"\x8e\x01\n" +
	"\aMPUPart\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1b\n" +
	"\tupload_id\x18\x03 \x01(\tR\buploadId\x12\x1f\n" +
	"\vpart_number\x18\x04 \x01(\x05R\n" +
	"partNumber\x12\x1b\n" +
	"\tpart_data\x18\x05 \x01(\fR\bpartData\"\x96\x01\n" +
	"\vMPUComplete\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1b\n" +
	"\tupload_id\x18\x03 \x01(\tR\buploadId\x12!\n" +
	"\fpart_numbers\x18\x04 \x03(\x05R\vpartNumbers\x12\x1d\n" +
	"\n" +
	"part_etags\x18\x05 \x03(\tR\tpartEtags\"Q\n" +
	"\bMPUAbort\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1b\n" +
	"\tupload_id\x18\x03 \x01(\tR\buploadId\"S\n" +
	"\x0fBucketOpRequest\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"@\n" +
	"\x10BucketOpResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"7\n" +
	"\bRefDelta\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\tR\x06hashes\x12\x13\n" +
	"\x05op_id\x18\x02 \x01(\tR\x04opId\"\\\n" +
	"\fLeaseRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"E\n" +
	"\rCatchupCursor\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x19\n" +
	"\blast_seq\x18\x02 \x01(\x04R\alastSeq\"_\n" +
	"\bWALEntry\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x03R\x02ts\x12\x17\n" +
	"\aop_type\x18\x03 \x01(\tR\x06opType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\")\n" +
	"\rLayoutRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\"5\n" +
	"\x0eLayoutResponse\x12#\n" +
	"\rsigned_layout\x18\x01 \x01(\fR\fsignedLayout\">\n" +
	"\x04KVOp\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"-\n" +
	"\x05KVAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"+\n" +
	"\rKVBulkRequest\x12\x1a\n" +
	"\bprefixes\x18\x01 \x03(\fR\bprefixes\"1\n" +
	"\aKVEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"u\n" +
	"\vJoinRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\tR\x04zone\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x03R\bcapacity\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"e\n" +
	"\fJoinResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12#\n" +
	"\rsigned_layout\x18\x03 \x01(\fR\fsignedLayout2\xc2\x10\n" +
	"\aCluster\x12B\n" +
	"\tHandshake\x12\x18.hangar.cluster.v1.Hello\x1a\x1b.hangar.cluster.v1.HelloAck\x12Q\n" +
	"\x0fHeartbeatStream\x12\x1c.hangar.cluster.v1.Heartbeat\x1a\x1c.hangar.cluster.v1.Heartbeat(\x010\x01\x12I\n" +
	"\bHasChunk\x12\x1b.hangar.cluster.v1.ChunkRef\x1a .hangar.cluster.v1.ChunkPresence\x12T\n" +
	"\tHasChunks\x12 .hangar.cluster.v1.ChunkRefBatch\x1a%.hangar.cluster.v1.ChunkPresenceBatch\x12J\n" +
	"\bPutChunk\x12\x1c.hangar.cluster.v1.ChunkData\x1a\x1e.hangar.cluster.v1.PutChunkAck(\x01\x12G\n" +
	"\bGetChunk\x12\x1b.hangar.cluster.v1.ChunkRef\x1a\x1c.hangar.cluster.v1.ChunkData0\x01\x12I\n" +
	"\x12DeleteChunkReplica\x12\x1b.hangar.cluster.v1.ChunkRef\x1a\x16.hangar.cluster.v1.Ack\x12I\n" +
	"\x0eAcquirePending\x12\x1f.hangar.cluster.v1.LeaseRequest\x1a\x16.hangar.cluster.v1.Ack\x12I\n" +
	"\x0eReleasePending\x12\x1f.hangar.cluster.v1.LeaseRequest\x1a\x16.hangar.cluster.v1.Ack\x12L\n" +
	"\vPutMetadata\x12\x1d.hangar.cluster.v1.MetadataOp\x1a\x1e.hangar.cluster.v1.MetadataAck\x12J\n" +
	"\vGetMetadata\x12\x1e.hangar.cluster.v1.MetadataKey\x1a\x1b.hangar.cluster.v1.Metadata\x12M\n" +
	"\x0eDeleteMetadata\x12\x1e.hangar.cluster.v1.MetadataKey\x1a\x1b.hangar.cluster.v1.Metadata\x12R\n" +
	"\fListMetadata\x12\x1e.hangar.cluster.v1.ListRequest\x1a .hangar.cluster.v1.MetadataEntry0\x01\x12K\n" +
	"\n" +
	"PutVersion\x12\x1d.hangar.cluster.v1.MetadataOp\x1a\x1e.hangar.cluster.v1.MetadataAck\x12I\n" +
	"\n" +
	"GetVersion\x12\x1e.hangar.cluster.v1.MetadataKey\x1a\x1b.hangar.cluster.v1.Metadata\x12L\n" +
	"\rDeleteVersion\x12\x1e.hangar.cluster.v1.MetadataKey\x1a\x1b.hangar.cluster.v1.Metadata\x12A\n" +
	"\vInitiateMPU\x12\x1a.hangar.cluster.v1.MPUPart\x1a\x16.hangar.cluster.v1.Ack\x12@\n" +
	"\n" +
	"PutMPUPart\x12\x1a.hangar.cluster.v1.MPUPart\x1a\x16.hangar.cluster.v1.Ack\x12M\n" +
	"\vCompleteMPU\x12\x1e.hangar.cluster.v1.MPUComplete\x1a\x1e.hangar.cluster.v1.MetadataAck\x12?\n" +
	"\bAbortMPU\x12\x1b.hangar.cluster.v1.MPUAbort\x1a\x16.hangar.cluster.v1.Ack\x12S\n" +
	"\bBucketOp\x12\".hangar.cluster.v1.BucketOpRequest\x1a#.hangar.cluster.v1.BucketOpResponse\x12>\n" +
	"\aIncRefs\x12\x1b.hangar.cluster.v1.RefDelta\x1a\x16.hangar.cluster.v1.Ack\x12>\n" +
	"\aDecRefs\x12\x1b.hangar.cluster.v1.RefDelta\x1a\x16.hangar.cluster.v1.Ack\x12Q\n" +
	"\x0eReplicaCatchup\x12 .hangar.cluster.v1.CatchupCursor\x1a\x1b.hangar.cluster.v1.WALEntry0\x01\x12P\n" +
	"\tGetLayout\x12 .hangar.cluster.v1.LayoutRequest\x1a!.hangar.cluster.v1.LayoutResponse\x12@\n" +
	"\vReplicateKV\x12\x17.hangar.cluster.v1.KVOp\x1a\x18.hangar.cluster.v1.KVAck\x12L\n" +
	"\n" +
	"BulkSyncKV\x12 .hangar.cluster.v1.KVBulkRequest\x1a\x1a.hangar.cluster.v1.KVEntry0\x01\x12G\n" +
	"\x04Join\x12\x1e.hangar.cluster.v1.JoinRequest\x1a\x1f.hangar.cluster.v1.JoinResponseB/Z-github.com/sowahq/hangar/internal/api/rpc;rpcb\x06proto3"

var (
	file_internal_api_rpc_service_proto_rawDescOnce sync.Once
	file_internal_api_rpc_service_proto_rawDescData []byte
)

func file_internal_api_rpc_service_proto_rawDescGZIP() []byte {
	file_internal_api_rpc_service_proto_rawDescOnce.Do(func() {
		file_internal_api_rpc_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_rpc_service_proto_rawDesc), len(file_internal_api_rpc_service_proto_rawDesc)))
	})
	return file_internal_api_rpc_service_proto_rawDescData
}

var file_internal_api_rpc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_internal_api_rpc_service_proto_goTypes = []any{
	(*Hello)(nil),              // 0: hangar.cluster.v1.Hello
	(*HelloAck)(nil),           // 1: hangar.cluster.v1.HelloAck
	(*Heartbeat)(nil),          // 2: hangar.cluster.v1.Heartbeat
	(*ChunkRef)(nil),           // 3: hangar.cluster.v1.ChunkRef
	(*ChunkPresence)(nil),      // 4: hangar.cluster.v1.ChunkPresence
	(*ChunkPresenceBatch)(nil), // 5: hangar.cluster.v1.ChunkPresenceBatch
	(*ChunkRefBatch)(nil),      // 6: hangar.cluster.v1.ChunkRefBatch
	(*ChunkData)(nil),          // 7: hangar.cluster.v1.ChunkData
	(*PutChunkAck)(nil),        // 8: hangar.cluster.v1.PutChunkAck
	(*Ack)(nil),                // 9: hangar.cluster.v1.Ack
	(*MetadataKey)(nil),        // 10: hangar.cluster.v1.MetadataKey
	(*MetadataOp)(nil),         // 11: hangar.cluster.v1.MetadataOp
	(*Metadata)(nil),           // 12: hangar.cluster.v1.Metadata
	(*MetadataAck)(nil),        // 13: hangar.cluster.v1.MetadataAck
	(*ListRequest)(nil),        // 14: hangar.cluster.v1.ListRequest
	(*MetadataEntry)(nil),      // 15: hangar.cluster.v1.MetadataEntry
	(*MPUPart)(nil),            // 16: hangar.cluster.v1.MPUPart
	(*MPUComplete)(nil),        // 17: hangar.cluster.v1.MPUComplete
	(*MPUAbort)(nil),           // 18: hangar.cluster.v1.MPUAbort
	(*BucketOpRequest)(nil),    // 19: hangar.cluster.v1.BucketOpRequest
	(*BucketOpResponse)(nil),   // 20: hangar.cluster.v1.BucketOpResponse
	(*RefDelta)(nil),           // 21: hangar.cluster.v1.RefDelta
	(*LeaseRequest)(nil),       // 22: hangar.cluster.v1.LeaseRequest
	(*CatchupCursor)(nil),      // 23: hangar.cluster.v1.CatchupCursor
	(*WALEntry)(nil),           // 24: hangar.cluster.v1.WALEntry
	(*LayoutRequest)(nil),      // 25: hangar.cluster.v1.LayoutRequest
	(*LayoutResponse)(nil),     // 26: hangar.cluster.v1.LayoutResponse
	(*KVOp)(nil),               // 27: hangar.cluster.v1.KVOp
	(*KVAck)(nil),              // 28: hangar.cluster.v1.KVAck
	(*KVBulkRequest)(nil),      // 29: hangar.cluster.v1.KVBulkRequest
	(*KVEntry)(nil),            // 30: hangar.cluster.v1.KVEntry
	(*JoinRequest)(nil),        // 31: hangar.cluster.v1.JoinRequest
	(*JoinResponse)(nil),       // 32: hangar.cluster.v1.JoinResponse
}
var file_internal_api_rpc_service_proto_depIdxs = []int32{
	4,  // 0: hangar.cluster.v1.ChunkPresenceBatch.entries:type_name -> hangar.cluster.v1.ChunkPresence
	3,  // 1: hangar.cluster.v1.ChunkRefBatch.refs:type_name -> hangar.cluster.v1.ChunkRef
	0,  // 2: hangar.cluster.v1.Cluster.Handshake:input_type -> hangar.cluster.v1.Hello
	2,  // 3: hangar.cluster.v1.Cluster.HeartbeatStream:input_type -> hangar.cluster.v1.Heartbeat
	3,  // 4: hangar.cluster.v1.Cluster.HasChunk:input_type -> hangar.cluster.v1.ChunkRef
	6,  // 5: hangar.cluster.v1.Cluster.HasChunks:input_type -> hangar.cluster.v1.ChunkRefBatch
	7,  // 6: hangar.cluster.v1.Cluster.PutChunk:input_type -> hangar.cluster.v1.ChunkData
	3,  // 7: hangar.cluster.v1.Cluster.GetChunk:input_type -> hangar.cluster.v1.ChunkRef
	3,  // 8: hangar.cluster.v1.Cluster.DeleteChunkReplica:input_type -> hangar.cluster.v1.ChunkRef
	22, // 9: hangar.cluster.v1.Cluster.AcquirePending:input_type -> hangar.cluster.v1.LeaseRequest
	22, // 10: hangar.cluster.v1.Cluster.ReleasePending:input_type -> hangar.cluster.v1.LeaseRequest
	11, // 11: hangar.cluster.v1.Cluster.PutMetadata:input_type -> hangar.cluster.v1.MetadataOp
	10, // 12: hangar.cluster.v1.Cluster.GetMetadata:input_type -> hangar.cluster.v1.MetadataKey
	10, // 13: hangar.cluster.v1.Cluster.DeleteMetadata:input_type -> hangar.cluster.v1.MetadataKey
	14, // 14: hangar.cluster.v1.Cluster.ListMetadata:input_type -> hangar.cluster.v1.ListRequest
	11, // 15: hangar.cluster.v1.Cluster.PutVersion:input_type -> hangar.cluster.v1.MetadataOp
	10, // 16: hangar.cluster.v1.Cluster.GetVersion:input_type -> hangar.cluster.v1.MetadataKey
	10, // 17: hangar.cluster.v1.Cluster.DeleteVersion:input_type -> hangar.cluster.v1.MetadataKey
	16, // 18: hangar.cluster.v1.Cluster.InitiateMPU:input_type -> hangar.cluster.v1.MPUPart
	16, // 19: hangar.cluster.v1.Cluster.PutMPUPart:input_type -> hangar.cluster.v1.MPUPart
	17, // 20: hangar.cluster.v1.Cluster.CompleteMPU:input_type -> hangar.cluster.v1.MPUComplete
	18, // 21: hangar.cluster.v1.Cluster.AbortMPU:input_type -> hangar.cluster.v1.MPUAbort
	19, // 22: hangar.cluster.v1.Cluster.BucketOp:input_type -> hangar.cluster.v1.BucketOpRequest
	21, // 23: hangar.cluster.v1.Cluster.IncRefs:input_type -> hangar.cluster.v1.RefDelta
	21, // 24: hangar.cluster.v1.Cluster.DecRefs:input_type -> hangar.cluster.v1.RefDelta
	23, // 25: hangar.cluster.v1.Cluster.ReplicaCatchup:input_type -> hangar.cluster.v1.CatchupCursor
	25, // 26: hangar.cluster.v1.Cluster.GetLayout:input_type -> hangar.cluster.v1.LayoutRequest
	27, // 27: hangar.cluster.v1.Cluster.ReplicateKV:input_type -> hangar.cluster.v1.KVOp
	29, // 28: hangar.cluster.v1.Cluster.BulkSyncKV:input_type -> hangar.cluster.v1.KVBulkRequest
	31, // 29: hangar.cluster.v1.Cluster.Join:input_type -> hangar.cluster.v1.JoinRequest
	1,  // 30: hangar.cluster.v1.Cluster.Handshake:output_type -> hangar.cluster.v1.HelloAck
	2,  // 31: hangar.cluster.v1.Cluster.HeartbeatStream:output_type -> hangar.cluster.v1.Heartbeat
	4,  // 32: hangar.cluster.v1.Cluster.HasChunk:output_type -> hangar.cluster.v1.ChunkPresence
	5,  // 33: hangar.cluster.v1.Cluster.HasChunks:output_type -> hangar.cluster.v1.ChunkPresenceBatch
	8,  // 34: hangar.cluster.v1.Cluster.PutChunk:output_type -> hangar.cluster.v1.PutChunkAck
	7,  // 35: hangar.cluster.v1.Cluster.GetChunk:output_type -> hangar.cluster.v1.ChunkData
	9,  // 36: hangar.cluster.v1.Cluster.DeleteChunkReplica:output_type -> hangar.cluster.v1.Ack
	9,  // 37: hangar.cluster.v1.Cluster.AcquirePending:output_type -> hangar.cluster.v1.Ack
	9,  // 38: hangar.cluster.v1.Cluster.ReleasePending:output_type -> hangar.cluster.v1.Ack
	13, // 39: hangar.cluster.v1.Cluster.PutMetadata:output_type -> hangar.cluster.v1.MetadataAck
	12, // 40: hangar.cluster.v1.Cluster.GetMetadata:output_type -> hangar.cluster.v1.Metadata
	12, // 41: hangar.cluster.v1.Cluster.DeleteMetadata:output_type -> hangar.cluster.v1.Metadata
	15, // 42: hangar.cluster.v1.Cluster.ListMetadata:output_type -> hangar.cluster.v1.MetadataEntry
	13, // 43: hangar.cluster.v1.Cluster.PutVersion:output_type -> hangar.cluster.v1.MetadataAck
	12, // 44: hangar.cluster.v1.Cluster.GetVersion:output_type -> hangar.cluster.v1.Metadata
	12, // 45: hangar.cluster.v1.Cluster.DeleteVersion:output_type -> hangar.cluster.v1.Metadata
	9,  // 46: hangar.cluster.v1.Cluster.InitiateMPU:output_type -> hangar.cluster.v1.Ack
	9,  // 47: hangar.cluster.v1.Cluster.PutMPUPart:output_type -> hangar.cluster.v1.Ack
	13, // 48: hangar.cluster.v1.Cluster.CompleteMPU:output_type -> hangar.cluster.v1.MetadataAck
	9,  // 49: hangar.cluster.v1.Cluster.AbortMPU:output_type -> hangar.cluster.v1.Ack
	20, // 50: hangar.cluster.v1.Cluster.BucketOp:output_type -> hangar.cluster.v1.BucketOpResponse
	9,  // 51: hangar.cluster.v1.Cluster.IncRefs:output_type -> hangar.cluster.v1.Ack
	9,  // 52: hangar.cluster.v1.Cluster.DecRefs:output_type -> hangar.cluster.v1.Ack
	24, // 53: hangar.cluster.v1.Cluster.ReplicaCatchup:output_type -> hangar.cluster.v1.WALEntry
	26, // 54: hangar.cluster.v1.Cluster.GetLayout:output_type -> hangar.cluster.v1.LayoutResponse
	28, // 55: hangar.cluster.v1.Cluster.ReplicateKV:output_type -> hangar.cluster.v1.KVAck
	30, // 56: hangar.cluster.v1.Cluster.BulkSyncKV:output_type -> hangar.cluster.v1.KVEntry
	32, // 57: hangar.cluster.v1.Cluster.Join:output_type -> hangar.cluster.v1.JoinResponse
	30, // [30:58] is the sub-list for method output_type
	2,  // [2:30] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_internal_api_rpc_service_proto_init() }
func file_internal_api_rpc_service_proto_init() {
	if File_internal_api_rpc_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_rpc_service_proto_rawDesc), len(file_internal_api_rpc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_rpc_service_proto_goTypes,
		DependencyIndexes: file_internal_api_rpc_service_proto_depIdxs,
		MessageInfos:      file_internal_api_rpc_service_proto_msgTypes,
	}.Build()
	File_internal_api_rpc_service_proto = out.File
	file_internal_api_rpc_service_proto_goTypes = nil
	file_internal_api_rpc_service_proto_depIdxs = nil
}
